name: "Check Flutter versions"
on:
  schedule:
    # Every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      
      - name: Ubuntu 18 Docker Install
        run: |
          sudo chmod +x ./setup/install_docker_ubuntu20.sh
          sh ./setup/install_docker_ubuntu20.sh
          

        
