name: "Check Flutter versions"
on:
  schedule:
    # Every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Debian 9 and Newer Docker Install
        run: |
          sudo chmod +x ./setup/install_docker_debian.sh
          sh ./setup/install_docker_debian.sh
          service docker start
          
      - name: Server Setup Script
        run: |
          sudo chmod +x ./setup/install.sh
          sh ./setup/install.sh
          
      - name: Start the Server
        run: sh ./start_scripts/start_sandfly.sh

        
